name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: MainEnv
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Semantic Release
        uses: paulhatch/semantic-version@v5.4.0
